version: '3.9'

services:
  postgres:
    container_name: chaindexing
    image: 'postgres:14'
    environment:
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      POSTGRES_DB: 'chaindexing_db'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
